"""Initial migration

Revision ID: a8136e54a2c8
Revises: 
Create Date: 2023-10-29 19:45:11.434447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8136e54a2c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('educator_upload', sa.String(length=255), nullable=True),
    sa.Column('student_upload', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('class')
    with op.batch_alter_table('educator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('drive_id', sa.Integer(), nullable=True))
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('educator_educator_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint('educator_school_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'school', ['school_id'], ['id'])
        batch_op.create_foreign_key(None, 'drive', ['drive_id'], ['id'])
        batch_op.drop_column('educator_name')
        batch_op.drop_column('educator_id')
        batch_op.drop_column('educator_password')
        batch_op.drop_column('educator_email')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('owner_owner_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('owner_password')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('owner_email')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('school_school_email_key', type_='unique')
        batch_op.drop_constraint('school_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'owner', ['owner_id'], ['id'])
        batch_op.drop_column('school_name')
        batch_op.drop_column('school_email')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('drive_id', sa.Integer(), nullable=True))
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('student_student_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_constraint('student_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('student_school_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'school', ['school_id'], ['id'])
        batch_op.create_foreign_key(None, 'drive', ['drive_id'], ['id'])
        batch_op.drop_column('student_name')
        batch_op.drop_column('student_email')
        batch_op.drop_column('student_password')
        batch_op.drop_column('class_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_school_id_fkey', 'school', ['school_id'], ['school_id'])
        batch_op.create_foreign_key('student_class_id_fkey', 'class', ['class_id'], ['class_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('student_student_email_key', ['student_email'])
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('drive_id')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('school_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('school_owner_id_fkey', 'owner', ['owner_id'], ['owner_id'])
        batch_op.create_unique_constraint('school_school_email_key', ['school_email'])
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), server_default=sa.text("nextval('owner_owner_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('owner_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('owner_owner_email_key', ['owner_email'])
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('educator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('educator_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('educator_password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('educator_id', sa.INTEGER(), server_default=sa.text("nextval('educator_educator_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('educator_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('educator_school_id_fkey', 'school', ['school_id'], ['school_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('educator_educator_email_key', ['educator_email'])
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('drive_id')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    op.create_table('class',
    sa.Column('class_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('educator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.educator_id'], name='class_educator_id_fkey'),
    sa.ForeignKeyConstraint(['school_id'], ['school.school_id'], name='class_school_id_fkey'),
    sa.PrimaryKeyConstraint('class_id', name='class_pkey')
    )
    op.drop_table('room')
    op.drop_table('resource')
    op.drop_table('note')
    op.drop_table('assessment')
    op.drop_table('drive')
    # ### end Alembic commands ###
